import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  CLIQ_HANDLER_SECRET_PLACEHOLDER,
  runCliqPrintHandlersCommand,
} from "./print-handlers-command.js";
import {
  CLIQ_HANDLER_SCHEMA_FIELD,
  CLIQ_HANDLER_SCHEMA_VERSION,
} from "./handler-schema.js";

const ROOT = join(new URL(".", import.meta.url).pathname, "..");
const URL_OK = "https://cliq.example.com/cliq/webhook";

function run(options: Parameters<typeof runCliqPrintHandlersCommand>[0]) {
  const lines: string[] = [];
  const errors: string[] = [];
  const code = runCliqPrintHandlersCommand(options, {
    writeLine: (line) => lines.push(line),
    writeError: (line) => errors.push(line),
  });
  return { code, text: lines.join("\n"), errors: errors.join("\n") };
}

describe("cliq print-handlers command (issue #247)", () => {
  it("renders separately labeled canonical Message and Mention scripts", () => {
    const result = run({ webhookUrl: URL_OK });
    expect(result.code).toBe(0);
    expect(result.text).toContain("=== message_handler (DMs) ===");
    expect(result.text).toContain("=== mention_handler (channels) ===");
    expect(result.text).toContain('payload.put("handler", "message")');
    expect(result.text).toContain('payload.put("handler", "mention")');
    expect(result.text).toContain(`payload.put("${CLIQ_HANDLER_SCHEMA_FIELD}", "${CLIQ_HANDLER_SCHEMA_VERSION}")`);
    expect(result.text).toContain('payload.put("eventId", eventId)');
    expect(result.text).toContain('response.put("eventId", eventId)');
    const [, message, mention] = result.text.split(/=== (?:message_handler \(DMs\)|mention_handler \(channels\)) ===/);
    expect(message).toContain("attachments");
    expect(mention).not.toContain("attachments");
  });

  it("uses the explicit secret only when supplied, otherwise an output-safe placeholder", () => {
    const configuredSecret = "configured-secret-must-not-leak";
    const omitted = run({
      cfg: { channels: { cliq: { publicWebhookUrl: URL_OK, webhookSecret: configuredSecret } } } as never,
    });
    expect(omitted.code).toBe(0);
    expect(omitted.text).toContain(CLIQ_HANDLER_SECRET_PLACEHOLDER);
    expect(omitted.text).not.toContain(configuredSecret);

    const explicit = run({ webhookUrl: URL_OK, webhookSecret: "explicit-console-secret" });
    expect(explicit.text).toContain("explicit-console-secret");
  });

  it("uses the configured URL when a flag is absent, while flags win", () => {
    const cfg = { channels: { cliq: { publicWebhookUrl: URL_OK } } } as never;
    expect(run({ cfg }).text).toContain(URL_OK);
    const override = "https://other.example.com/cliq/webhook";
    expect(run({ cfg, webhookUrl: override }).text).toContain(override);
  });

  it("rejects absent, non-HTTPS, and wrong-path URLs before rendering", () => {
    expect(run({}).code).toBe(2);
    expect(run({}).errors).toMatch(/Missing --webhook-url/);
    expect(run({ webhookUrl: "http://x.example.com/cliq/webhook" }).code).toBe(2);
    expect(run({ webhookUrl: "https://x.example.com/not-cliq" }).code).toBe(2);
  });

  it("emits a machine-readable shape with no configured secret fallback", () => {
    const result = run({
      webhookUrl: URL_OK,
      json: true,
      cfg: { channels: { cliq: { webhookSecret: "must-not-appear" } } } as never,
    });
    const json = JSON.parse(result.text) as Record<string, string>;
    expect(json.webhookUrl).toBe(URL_OK);
    expect(json.messageHandler).toContain(CLIQ_HANDLER_SECRET_PLACEHOLDER);
    expect(result.text).not.toContain("must-not-appear");
  });

  it("keeps the README manual handler blocks generated by the same canonical contract", () => {
    const readme = readFileSync(join(ROOT, "README.md"), "utf8");
    const result = run({ webhookUrl: "https://<gateway-host>/cliq/webhook", webhookSecret: "<the same secret you set as webhookSecret in openclaw.json>" });
    const firstScript = result.text
      .split("=== mention_handler (channels) ===")[0]
      .replace("=== message_handler (DMs) ===\n", "")
      .replace(/^webhookUrl = /m, "webhookUrl    = ")
      .replace(/^webhookSecret = /m, "webhookSecret = ");
    expect(readme).toContain(firstScript);
  });
});
